# Generated by Django 4.2.7 on 2023-11-06 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_inputimagemodel_outputimagemodel_delete_imagemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputimagemodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='yolo_in', verbose_name='유저 업로드 이미지'),
        ),
        migrations.AlterField(
            model_name='outputimagemodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='yolo_out', verbose_name='yolo 결과 이미지'),
        ),
    ]
