# Generated by Django 4.2.7 on 2023-11-14 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0003_alter_inputimagemodel_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight', models.IntegerField()),
                ('timestamp', models.IntegerField()),
            ],
        ),
    ]
